### ISSUE TITLE
Please upgrade dependencies

### ISSUE THREAD

**Issue by Whitie** [DexcTrack/dexctrack#17]
All major Linux distributions ship with Python 3.10+ today. If you pip install (please remove sudo and use a Virtualenv) the dependencies, you get:
```
...
matplotlib==3.9.2
numpy==2.1.2
Pympler==1.1
pyserial==3.5
pytz==2024.2
tzlocal==5.2
...
```
This leads to an error with matplotlib, because the arguments from Slider have changed a bit. When this error is fixed you get an error from numpy and so on. Trying to install old versions of the libs in a Virtualenv is not an option, because than the Software hangs at a `lock.acquire` forever.

**Comment by DexcTrack** [comment]
@Whitie Yesterday, I merged in an update to support the more recent versions of the matplot library. I also tried using a python virtual environment. That was successful for me. I've tried to update the instructions to offer that as an option. I tried to simplify the instructions a bit, but I'm not sure that they work for all scenarios.

Try updating your code using
```
cd dexctrack
git pull origin master
```
and see if I've fixed it for you.
