### ISSUE TITLE
dexctrack crashes when connected using a dexcom g6

### ISSUE THREAD

**Issue by Testostheron1963-de** [DexcTrack/dexctrack#7]
Hello,
i tested your program under Debian 10.2 an I found, that the program crashes if there is an existing database in my home directory. If the database doesn't exist, it will be created but there is no graph visible inside the diagram.

if the database is already created when stating your program it crashes immediatly.
Using the debug functionality of your sourcecode I can read the following lines of output:

//******************************************************************************************************************
python2.7 ./dexctrack.py -d
DexcTrack  Copyright (C) 2018  Steve Erlenborn
This program comes with ABSOLUTELY NO WARRANTY.

get_screen_size width = 1920 , get_screen_size height = 1080 , dispRatio = 1.8
sys.platform = linux2
backend = TkAgg
sqlite_file = /home/bert/dexc_PL85138430.sqlite
rcParams[timezone] = Europe/Berlin
Latest glucose at 2020-01-29 00:18:21+01:00 = 143
2 hour prediction : at 2020-01-29 02:18:21+01:00 glucose = 143.0
sizeof(calibdata) = 0
Traceback (most recent call last):
  File "./dexctrack.py", line 3377, in <module>
    plotGraph()
  File "./dexctrack.py", line 2919, in plotGraph
    cx = calibdata[:, 0] # sysSeconds
IndexError: too many indices for array
*****************
Close in progress
*****************
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/_pylab_helpers.py", line 78, in destroy_all
    manager.destroy()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py", line 560, in destroy
    self.window.destroy()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1873, in destroy
    self.tk.call('destroy', self._w)
TclError: can't invoke "destroy" command: application has been destroyed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/_pylab_helpers.py", line 78, in destroy_all
    manager.destroy()
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py", line 560, in destroy
    self.window.destroy()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1873, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed

//******************************************************************************************************************

I opened the existing database in my home directory I could see that there are no records stored in the Calib table.

**Comment by DexcTrack** [comment]
Thanks for reporting this issue. I never noticed it because I've always had calibrations in my database since I added the display of them on the graph. I've submitted a fix. Please grab the latest version of dexctrack.py and test it on your system. Running '**git pull origin master**' will pull in the updated code.
Please let me know if this removes the crash.

**Comment by Testostheron1963-de** [comment]
Thank you so much !
I tried to debug the code but I'm not an expert in using Python.
I will test your solution.

Again: Thank you so much !

Steve Erlenborn <notifications@github.com> schrieb am Di., 4. Feb. 2020,
02:54:

**Comment by Testostheron1963-de** [comment]
After testing your bugfix on my machine, it functions perfectly.
Thank you so much for your help !
